package com.cheng.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cheng.content.DBMoment.DBMainEntity;
import com.cheng.content.v2ex.V2exEntity;

import com.cheng.db.DBMainEntityDao;
import com.cheng.db.V2exEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBMainEntityDaoConfig;
    private final DaoConfig v2exEntityDaoConfig;

    private final DBMainEntityDao dBMainEntityDao;
    private final V2exEntityDao v2exEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBMainEntityDaoConfig = daoConfigMap.get(DBMainEntityDao.class).clone();
        dBMainEntityDaoConfig.initIdentityScope(type);

        v2exEntityDaoConfig = daoConfigMap.get(V2exEntityDao.class).clone();
        v2exEntityDaoConfig.initIdentityScope(type);

        dBMainEntityDao = new DBMainEntityDao(dBMainEntityDaoConfig, this);
        v2exEntityDao = new V2exEntityDao(v2exEntityDaoConfig, this);

        registerDao(DBMainEntity.class, dBMainEntityDao);
        registerDao(V2exEntity.class, v2exEntityDao);
    }
    
    public void clear() {
        dBMainEntityDaoConfig.clearIdentityScope();
        v2exEntityDaoConfig.clearIdentityScope();
    }

    public DBMainEntityDao getDBMainEntityDao() {
        return dBMainEntityDao;
    }

    public V2exEntityDao getV2exEntityDao() {
        return v2exEntityDao;
    }

}
