package com.cheng.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cheng.content.v2ex.V2exEntity;

import com.cheng.db.V2exEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig v2exEntityDaoConfig;

    private final V2exEntityDao v2exEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        v2exEntityDaoConfig = daoConfigMap.get(V2exEntityDao.class).clone();
        v2exEntityDaoConfig.initIdentityScope(type);

        v2exEntityDao = new V2exEntityDao(v2exEntityDaoConfig, this);

        registerDao(V2exEntity.class, v2exEntityDao);
    }
    
    public void clear() {
        v2exEntityDaoConfig.clearIdentityScope();
    }

    public V2exEntityDao getV2exEntityDao() {
        return v2exEntityDao;
    }

}
