package com.cheng.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cheng.content.v2ex.V2exHotTopicEntity;

import com.cheng.db.V2exHotTopicEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig v2exHotTopicEntityDaoConfig;

    private final V2exHotTopicEntityDao v2exHotTopicEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        v2exHotTopicEntityDaoConfig = daoConfigMap.get(V2exHotTopicEntityDao.class).clone();
        v2exHotTopicEntityDaoConfig.initIdentityScope(type);

        v2exHotTopicEntityDao = new V2exHotTopicEntityDao(v2exHotTopicEntityDaoConfig, this);

        registerDao(V2exHotTopicEntity.class, v2exHotTopicEntityDao);
    }
    
    public void clear() {
        v2exHotTopicEntityDaoConfig.clearIdentityScope();
    }

    public V2exHotTopicEntityDao getV2exHotTopicEntityDao() {
        return v2exHotTopicEntityDao;
    }

}
